### PR TITLE
add support for stable tag in unordered Markdown lists in README

### LINKED ISSUE #25: Support REAME.md with list headers
**Describe the bug**
> Could not get stable tag from README.md

The stable tag in the README.md was  as `* Stable tag: 2.1.2`.

**Steps to Reproduce**

1. Create a README.md with a Markdown list for the headers.
2. Run deployment
3. See error "Could not get stable tag from README.md"

**Expected behavior**
Be able to get the stable tag regardless if it is a list or not.

**Additional context**

The code responsible:
https://github.com/10up/action-wordpress-plugin-asset-update/blob/78630c5a75476c993066e833e2de6f20a29be777/entrypoint.sh#L115_L118

By removing `^` in `grep -m 1 "^Stable tag:" "$TMP_DIR/$README_NAME"`  would fix the bug.

WordPress.org parses the headers as follows.
https://github.com/WordPress/wordpress.org/blob/master/wordpress.org/public_html/wp-content/plugins/plugin-directory/readme/class-parser.php#L235-L253

As a temp fix I have switched for a list to using line breaks with two trailing whitespaces.

### PR DESCRIPTION
**Pull request by stklcode**
### Description of the Change

Extend the regular expression for stable tag extraction from `^Stable tag:` to `^([*+-]\s+)?Stable tag:`.

Doing so both forms

```
Stable tag:    1.2.3
```

and

```markdown
* Stable tag:   1.2.3
```

```markdown
- Stable tag:   1.2.3
```

```markdown
+ Stable tag:   1.2.3
```

are supported.

Using `grep -E` for extended regular expression, support required for the optional group.

### Alternate Designs

The proposed workaround in #25 was to remove the start of line expression, i.e. use only `Stable tag:`. This solution would also match the "Stable tag:" phrase anywhere within the text. However unlikely to appear, this is definitely not intended.

### Benefits

The action now properly supports Markdown README files with unordered lists.

### Possible Drawbacks

Assuming `grep -E` is available in any environment and a couple of microseconds for the extended regex processing doesn't matter, I can't think of any real drawback.

### Verification Process

Change the README file from plain text
```
=== My Plugin ===
Contributors:      Contri Butor
Requires at least: 4.0
Tested up to:      5.7
Requires PHP:      7.0
Stable tag:        1.2.3
License:           GPLv2 or later
License URI:       https://www.gnu.org/licenses/gpl-2.0.html
```

to Markdown

```markdown
# My Plugin
* Contributors:      Contri Butor
* Requires at least: 4.0
* Tested up to:      5.7
* Requires PHP:      7.0
* Stable tag:        1.2.3
* License:           GPLv2 or later
* License URI:       https://www.gnu.org/licenses/gpl-2.0.html
``` 

(equivalent with dash `-` or plus `+` instead of the asterisk `*`)

The action should no longer raise "Could not get stable tag from README.md" for the latter and update the tag (here: 1.2.3) accordingly.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

resolves #25

### Added
- Support for unordered Markdown lists in `README.md` for stable tag declaration.

### CODE REVIEW

**Comment by helen** [comment]
Thanks for the PR! Which flavor of `grep` have you tested this with (BSD vs. GNU)? I've run into some issues previously with differences between local (Mac, BSD) and the Actions runner (Ubuntu, GNU), so I'm pretty hesitant to merge until it's been proven tested on the GNU version.

**Comment by stklcode** [comment]
Good point.
I've written and tested the change in my local GNU environment.

Result look identical in GNU grep 3.4 (Linux) and BSD grep 2.5 (macOS). The RegEx does not rely on greedy/lazy search, which is (as far as I remember) the main difference between both implementations.

No formal proof, but unless we add testcases in both environments, we're likely stuck to manual testing.

gnugrep34
(GNU grep 3.4 on Fedora 33)

gnugrep34-ubuntu
(GNU grep 3.4 on Ubuntu focal (latest) Container)

bsdgrep25
(BSD grep 2.5 on macOS 10.13)

**Review by grappler — APPROVED** [review]
> The proposed workaround in #25 was to remove the start of line expression, i.e. use only `Stable tag:`. This solution would also match the "Stable tag:" phrase anywhere within the text. However unlikely to appear, this is definitely not intended.

Yes, the suggested solution makes more sense. I tested the regex and that makes sense.

**Comment by stklcode** [comment]
Any updates on this?
Is there any additional feedback required or just postponed?

I could provide a unit test for the changes. Simple GH actions workflow, atest shell script with intercepted subversion command (to mock the w.org repo without reconfiguration) would come to my mind. Execute some runs and verify files have been updated. But there are no tests yet, so I'm unsure if this would fit the desired project scope.

**Review by helen — APPROVED** [review]
I would love tests at some point but am okay with merging this for the moment, just hadn't gotten around to wrapping my head around a new release for this action until now.

**Pull request merged**
